import React from 'react';
import { Scale, Mail } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div>
      {/* Page Header */}
      <section className="section section-dark" style={{ padding: '4rem 0', borderBottom: '4px solid var(--color-safety-orange)' }}>
        <div className="container" style={{ textAlign: 'center' }}>
          <h1 style={{ color: '#fff', fontSize: '2.5rem', textTransform: 'uppercase', marginBottom: '0.5rem', fontWeight: 800 }}>Terms of Service</h1>
          <p style={{ color: '#cbd5e1', maxWidth: '600px', margin: '0 auto', fontSize: '1.1rem' }}>
            Review the terms governing project estimates, building materials delivery, and vehicle/operator leases.
          </p>
        </div>
      </section>

      {/* Terms Details */}
      <section className="section">
        <div className="container" style={{ maxWidth: '800px' }}>
          <div style={{ background: 'white', padding: '3rem 2rem', borderRadius: '8px', border: '1px solid var(--color-concrete-dark)', boxShadow: 'var(--shadow-sm)' }}>
            
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '2rem', borderBottom: '2px solid var(--color-concrete-base)', paddingBottom: '1rem' }}>
              <Scale size={28} style={{ color: 'var(--color-safety-orange)' }} />
              <h2 style={{ fontSize: '1.5rem', margin: 0, textTransform: 'uppercase', fontWeight: 800 }}>User Agreement & Disclaimers</h2>
            </div>

            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
              Effective Date: July 18, 2026. By accessing this website or submitting estimate requests, you agree to comply with and be bound by the following terms of service.
            </p>

            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', fontWeight: 700, marginTop: '2rem', marginBottom: '0.75rem' }}>1. Budget Estimations & Pricing Quotes</h3>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
              Any estimates generated by the online calculator or sent via email are <strong>approximate values</strong> for planning purposes only. They are based on plain site conditions and standard built-up parameters. Final contracting pricing is subject to structural checks, soil tests, blueprint updates, and formal written contracts.
            </p>

            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', fontWeight: 700, marginTop: '2rem', marginBottom: '0.75rem' }}>2. Material Supply & Deliveries</h3>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
              GPR Construction supplies building materials (such as M Sand, P Sand, blue metal aggregates, bricks, and steel) directly to site logistics corridors. Delivery times are subject to transit conditions, regional vehicle restriction regulations, and safe vehicular site access.
            </p>

            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', fontWeight: 700, marginTop: '2rem', marginBottom: '0.75rem' }}>3. Machinery & Fleet Leasing</h3>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
              All heavy machinery (JCB loaders, tractors, tipping lorries) leased through GPR are supplied with certified commercial operators. Leases are calculated based on operational hours or tonnage shifts. We are not liable for delays caused by severe weather anomalies, local utility line blockages, or mechanical anomalies.
            </p>

            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', fontWeight: 700, marginTop: '2rem', marginBottom: '0.75rem' }}>4. Uploaded Drawings & Copyrights</h3>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
              You warrant that you own the rights to, or have acquired the appropriate licenses for, any architectural blueprints, site sketches, or layouts uploaded through our form. GPR Construction holds no liability for copyright infringement claims regarding uploaded plan references.
            </p>

            <h3 style={{ fontSize: '1.2rem', textTransform: 'uppercase', fontWeight: 700, marginTop: '2rem', marginBottom: '0.75rem' }}>5. Governing Law</h3>
            <p style={{ color: 'var(--color-text-muted)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
              These terms are governed by and construed in accordance with the laws of the State of Tamil Nadu, India, without regard to conflict of law principles.
            </p>

            <div style={{ marginTop: '3rem', borderTop: '2px solid var(--color-concrete-base)', paddingTop: '1.5rem', display: 'flex', alignItems: 'center', gap: '1rem', background: 'var(--color-concrete-base)', padding: '1.5rem', borderRadius: '6px' }}>
              <Mail size={36} style={{ color: 'var(--color-steel-blue)', flexShrink: 0 }} />
              <div>
                <h4 style={{ margin: 0, textTransform: 'uppercase', fontSize: '0.9rem', fontWeight: 700 }}>Contract Administration</h4>
                <p style={{ margin: '0.25rem 0 0 0', color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>
                  Have questions about our service clauses or operator leases? Email us at <a href="mailto:gprconstruction2@gmail.com" style={{ color: 'var(--color-steel-blue)', fontWeight: 600 }}>gprconstruction2@gmail.com</a>.
                </p>
              </div>
            </div>

          </div>
        </div>
      </section>
    </div>
  );
}
